### ISSUE TITLE
Deploy error - mirror: Login failed: 500 OOPS: cannot change directory:/home/******

### ISSUE THREAD

**Issue by zeronacer** [christophschlosser/drone-ftps#22]
When Drone executes my deploy step, I get the following error:
`mirror: Login failed: 500 OOPS: cannot change directory:/home/******`

This is my .drone.yml step (___ is censored):
```
  - name: deploy
    image: cschlosser/drone-ftps
    environment:
      FTP_USERNAME:
        from_secret: FTP_USERNAME
      FTP_PASSWORD:
        from_secret: FTP_PASSWORD
      PLUGIN_HOSTNAME: ___
      PLUGIN_DEST_DIR: /opt/wwwhome/___/static_site
      PLUGIN_SECURE: false
      PLUGIN_INCLUDE: index.html|style.css
```

From what I understand, this means that the DEST_DIR is not resolved from the server root, but from the /home directory? If yes, how to set it up right?
