### ISSUE TITLE
Stuck on master_build step

### ISSUE THREAD

**Issue by morvy** [christophschlosser/drone-ftps#23]
Hi,

sorry for opening an issue but I am trying to get drone to upload pushed commit to FTP with no luck.

My .drone.yml looks like this:
```
kind: pipeline
name: default

steps:
- name: master_build
  image: cschlosser/drone-ftps
  environment:
    FTP_USERNAME:
      from_secret: username
    FTP_PASSWORD:
      from_secret: password
    PLUGIN_HOSTNAME: mytestftp.com:21
    PLUGIN_SECURE: false
    PLUGIN_VERIFY: false
    PLUGIN_EXCLUDE: ^\.git/$
```

..so it's 1:1 to the example here, secrets are set under username and password in drone repository secrets. I've also tried config I found on drone plugins site, with no luck too. If I add when clause, it won't trigger at all

In log I'm stuck on this message:
```
latest: Pulling from cschlosser/drone-ftps
Digest: sha256:7442ec050d7b05c3ff4f14e92e9bb0def4028ba555844591815434de8a5fe8ee
Status: Image is up to date for cschlosser/drone-ftps:latest
```

Any idea what I'm doing wrong?
Thanks!
